import math, sys

t = (1.0 + 5.0 ** 0.5) / 2.0
base = [(-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0),
        (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
        (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1)]
faces = [(0,11,5),(0,5,1),(0,1,7),(0,7,10),(0,10,11),(1,5,9),(5,11,4),(11,10,2),
         (10,7,6),(7,1,8),(3,9,4),(3,4,2),(3,2,6),(3,6,8),(3,8,9),(4,9,5),
         (2,4,11),(6,2,10),(8,6,7),(9,8,1)]

def norm(v):
    l = math.sqrt(sum(c*c for c in v)); return tuple(c/l for c in v)

level = int(sys.argv[1])
verts = [norm(v) for v in base]
tris = list(faces)
for _ in range(level):
    cache, nxt = {}, list(tris)
    def mid(a, b):
        k = (min(a,b), max(a,b))
        if k not in cache:
            m = norm(tuple((verts[a][i]+verts[b][i])*0.5 for i in range(3)))
            verts.append(m); cache[k] = len(verts)-1
        return cache[k]
    for (a,b,c) in tris:
        ab, bc, ca = mid(a,b), mid(b,c), mid(c,a)
        nxt += [(a,ab,ca),(b,bc,ab),(c,ca,bc),(ab,bc,ca)]
    tris = nxt

out = ['# Subdivided icosahedron (geodesic sphere), radius 1, %d triangles.' % len(tris),
       '# Generated by scripts/genIcosphere.py %d; plain OBJ v/f only.' % level,
       '# Vertex normals are recovered by the renderer from the shared vertices.']
for v in verts:
    out.append('v %.6f %.6f %.6f' % v)
for (a,b,c) in tris:
    out.append('f %d %d %d' % (a+1, b+1, c+1))
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
print('%d vertices, %d triangles -> %s' % (len(verts), len(tris), sys.argv[2]))
